### ISSUE TITLE
Publish provider to Terraform registry

### ISSUE THREAD

**Issue by pablo-ruth** [claranet/terraform-provider-zabbix#18]
Hello,

With the release of Terraform 0.13 it's now possible to publish custom providers to Terraform registry, allowing automatic installation of them during `terraform init`.

There is a guide here: https://www.terraform.io/docs/registry/providers/publishing.html

Are you planning to do it ?

**Comment by azman0101** [comment]
I've successfully publishing binaries for different architecture of provider following this doc https://www.terraform.io/docs/registry/providers/publishing.html#publishing-to-the-registry

https://github.com/oxa-test/terraform-provider-zabbix/releases

But while publishing, I'm hitting this error 
<img width="1431" alt="Capture d’écran 2020-10-07 à 12 39 05" src="https://user-images.githubusercontent.com/111579/95320755-3ad5ad80-089a-11eb-8cd7-46a0a8eebb60.png">

**Comment by pablo-ruth** [comment]
Have you added the GPG key to your Terraform Registry account? https://registry.terraform.io/settings/gpg-keys

**Comment by azman0101** [comment]
> Have you added the GPG key to your Terraform Registry account? https://registry.terraform.io/settings/gpg-keys

Yeah, I followed the above mentioned procedure. I will delete it and retry soon

**Comment by pablo-ruth** [comment]
Thanks for the release!
