### ISSUE TITLE
Zabbix Proxy

### ISSUE THREAD

**Issue by calvinjks** [claranet/terraform-provider-zabbix#52]
Is there a way you can add a proxy to your documentation?

**Comment by pdecat** [comment]
Hi, I'm not sure what you are requesting. Could you give more details and context?

**Comment by calvinjks** [comment]
I used your zabbix documentation to create a host, but I also need to create a proxy for that host. Could you update your documentation with a "proxy" resource?

**Comment by pdecat** [comment]
Ok, I get it now. Sadly, it is not just a matter of documentation.
This terraform provider does not support creating Zabbix proxies.

There's already an issue for that https://github.com/claranet/terraform-provider-zabbix/issues/26, some I'm closing this one as a duplicate.

**Comment by calvinjks** [comment]
Okay, thank you a lot!
